"""
SGP-Tribe3 - Generate 1000-Stimulus Bank
=========================================
Generates 100 text stimuli per category across 10 categories (1000 total).

Usage:
    python generate_stimulus_bank.py

Output (NEW, no overwrites):
    - data/stimulus_bank.json
"""

import os
import json
from datetime import datetime

CATEGORIES = {
    "simple": {
        "expected": ["G2_wernicke", "G7_sensory"],
        "texts": [
            "The cat sat quietly on the windowsill.",
            "A small bird sang from the garden fence.",
            "The morning dew glistened on the grass.",
            "She opened the wooden door with a gentle push.",
            "The old book rested on the dusty shelf.",
            "Rain fell softly on the cobblestone street.",
            "He poured warm milk into the ceramic mug.",
            "The clock chimed midnight in the quiet house.",
            "Flowers bloomed along the garden pathway.",
            "The dog slept peacefully on the rug.",
            "A candle flickered in the dim room.",
            "The river flowed gently through the meadow.",
            "She placed the letter in the envelope.",
            "The wind rustled the autumn leaves.",
            "He walked slowly down the winding path.",
            "The kettle whistled on the stove.",
            "Snow covered the rooftops in white.",
            "The lamp cast a warm glow on the desk.",
            "A butterfly landed on the flower petal.",
            "The train arrived at the station on time.",
            "She watered the plants on the balcony.",
            "The moon rose above the dark horizon.",
            "He folded the newspaper and set it aside.",
            "The cat stretched lazily in the sunlight.",
            "A gentle breeze carried the scent of pine.",
            "The baker arranged fresh bread on the counter.",
            "She tied her shoelaces and headed outside.",
            "The pond reflected the clear blue sky.",
            "He lit a match and struck it against the box.",
            "The garden gate creaked in the wind.",
            "A spider wove its web between two branches.",
            "The teapot steamed on the kitchen table.",
            "She brushed her hair in front of the mirror.",
            "The fence surrounded the small backyard.",
            "He swept the leaves from the front porch.",
            "The mailbox stood at the end of the driveway.",
            "A robin perched on the telephone wire.",
            "The curtains fluttered in the open window.",
            "She planted seeds in the prepared soil.",
            "The path led through the quiet forest.",
            "He polished the silver spoon until it shone.",
            "The fountain bubbled in the town square.",
            "A squirrel gathered acorns near the oak tree.",
            "The wallpaper featured a pattern of roses.",
            "She arranged the photographs in the album.",
            "The hammock swayed between two palm trees.",
            "He trimmed the hedges along the driveway.",
            "The ice melted in the glass of water.",
            "A cloud drifted across the bright sun.",
            "The wooden chair creaked as she sat down.",
            "She hung the painting on the living room wall.",
            "The garden hose coiled neatly by the shed.",
            "He fed the goldfish their morning flakes.",
            "The porch swing moved back and forth slowly.",
            "A snail crawled across the wet stone.",
            "The fireplace crackled with burning logs.",
            "She sorted the mail at the kitchen table.",
            "The umbrella stood in the corner by the door.",
            "He wound the grandfather clock carefully.",
            "The garden sprinkler watered the lawn evenly.",
            "A ladybug crawled along the window sill.",
            "The towel hung from the bathroom rack.",
            "She peeled an orange at the breakfast table.",
            "The mailbox flag was raised with new mail.",
            "He stacked firewood beside the cabin wall.",
            "The wind chime tinkled in the summer breeze.",
            "A frog sat on a lily pad in the pond.",
            "The doormat welcomed visitors to the house.",
            "She pruned the rose bushes with sharp shears.",
            "The streetlamp illuminated the quiet sidewalk.",
            "He washed the dishes in warm soapy water.",
            "The bird feeder hung from the maple branch.",
            "A moth fluttered around the porch light.",
            "The garden path was lined with smooth stones.",
            "She knitted a scarf by the fireside.",
            "The rain barrel collected water from the roof.",
            "He raked the gravel driveway smooth.",
            "The sunflower turned toward the morning light.",
            "A dragonfly hovered above the garden pond.",
            "The welcome mat sat in front of the door.",
            "She dusted the bookshelf with a soft cloth.",
            "The garden wall was covered in ivy.",
            "He sharpened the kitchen knives carefully.",
            "The birdbath held fresh water for visitors.",
            "A woodpecker tapped on the old tree trunk.",
            "The laundry hung on the outdoor clothesline.",
            "She arranged fresh flowers in a glass vase.",
            "The garden bench offered a quiet resting spot.",
            "He oiled the hinges on the garden gate.",
            "The compost bin sat in the corner of the yard.",
            "A butterfly emerged from its chrysalis.",
            "The garden trellis supported climbing vines.",
            "She swept the front steps clean of debris.",
            "The raindrop slid down the window pane.",
            "He planted tulip bulbs in the fall soil.",
            "The garden shed stored tools and supplies.",
            "A sparrow hopped along the garden path.",
            "The stone wall separated the two properties.",
            "She watered the herb garden every evening.",
            "The garden gnome stood among the petunias.",
            "He repaired the broken fence post quickly.",
            "The morning glory bloomed on the trellis.",
            "A bee buzzed around the lavender bush.",
            "The garden path curved around the old oak.",
            "She harvested ripe tomatoes from the vine.",
            "The garden pond reflected the evening sky.",
            "He mulched the flower beds before winter.",
        ]
    },
    "logical": {
        "expected": ["G4_pfc", "G1_broca"],
        "texts": [
            "If all squares are rectangles, and all rectangles are shapes, then all squares are shapes.",
            "The negation of a universal statement produces an existential statement.",
            "In formal logic, modus ponens allows us to infer Q from P and P implies Q.",
            "The union of two sets includes all elements from both sets without duplication.",
            "A tautology is a statement that is true under every possible interpretation.",
            "If no mammals are fish, and all whales are mammals, then no whales are fish.",
            "The law of excluded middle states that every proposition is either true or false.",
            "In set theory, the empty set is a subset of every set including itself.",
            "A valid argument guarantees that true premises lead to a true conclusion.",
            "The contrapositive of if P then Q is if not Q then not P, and they are equivalent.",
            "Mathematical induction proves a base case and then shows the inductive step.",
            "The intersection of disjoint sets contains no elements and equals the empty set.",
            "If some A are not B, then it cannot be true that all A are B.",
            "De Morgan laws state that the negation of a conjunction equals the disjunction of negations.",
            "A bijective function is both injective and surjective, establishing a one-to-one correspondence.",
            "If every prime greater than two is odd, and three is prime and greater than two, then three is odd.",
            "The pigeonhole principle states that if more items than containers exist, at least one container holds multiple items.",
            "In propositional logic, a contradiction is a statement that is always false.",
            "The distributive property of sets states that A intersected with B union C equals A intersect B union A intersect C.",
            "If all triangles have three sides, and this figure has four sides, then this figure is not a triangle.",
            "The commutative property of addition states that changing the order of addends does not change the sum.",
            "A necessary condition must be present for the outcome, but may not be sufficient alone.",
            "If all humans need oxygen, and Socrates is human, then Socrates needs oxygen.",
            "The power set of a set with n elements contains exactly two to the power of n elements.",
            "In logic, an argument is sound if it is valid and all its premises are actually true.",
            "The associative property of multiplication states that grouping does not affect the product.",
            "If no reptiles have fur, and all snakes are reptiles, then no snakes have fur.",
            "A sufficient condition guarantees the outcome, but the outcome may occur without it.",
            "The complement of a set contains all elements not in that set within the universal set.",
            "If all even numbers are divisible by two, and seven is not divisible by two, then seven is not even.",
            "In Boolean algebra, the identity element for AND is true, and for OR is false.",
            "If all multiples of six are multiples of three, and twelve is a multiple of six, then twelve is a multiple of three.",
            "The transitive property states that if A equals B and B equals C, then A equals C.",
            "A counterexample is sufficient to disprove a universal claim but cannot prove one.",
            "If all birds have feathers, and penguins are birds, then penguins have feathers.",
            "The Cartesian product of two sets produces all ordered pairs from their elements.",
            "If no circles have corners, and this shape has corners, then this shape is not a circle.",
            "In predicate logic, the universal quantifier asserts that a property holds for all elements.",
            "If all integers are real numbers, and five is an integer, then five is a real number.",
            "The symmetric difference of two sets contains elements in exactly one of the sets.",
            "If all squares have four equal sides, and this quadrilateral has unequal sides, then it is not a square.",
            "A fallacy is an error in reasoning that renders an argument logically invalid.",
            "If all metals conduct electricity, and copper is a metal, then copper conducts electricity.",
            "The identity property of addition states that any number plus zero equals the original number.",
            "If no triangles have four sides, and this shape has four sides, then this shape is not a triangle.",
            "In logic, affirming the consequent is a formal fallacy of the form if P then Q, Q, therefore P.",
            "If all whales are mammals, and no mammals are cold-blooded, then no whales are cold-blooded.",
            "The zero property of multiplication states that any number multiplied by zero equals zero.",
            "If all planets orbit a star, and Earth is a planet, then Earth orbits a star.",
            "A necessary and sufficient condition means that two statements are logically equivalent.",
            "If all right triangles satisfy the Pythagorean theorem, and this triangle is right, then it satisfies the theorem.",
            "The reflexive property states that every element is related to itself in an equivalence relation.",
            "If all gases expand when heated, and oxygen is a gas, then oxygen expands when heated.",
            "In set theory, two sets are equal if and only if they contain exactly the same elements.",
            "If all prime numbers greater than two are odd, and fifteen is odd, this does not prove fifteen is prime.",
            "The substitution property of equality states that if a equals b, then a can replace b in any expression.",
            "If all mammals are warm-blooded, and dolphins are mammals, then dolphins are warm-blooded.",
            "A valid deductive argument preserves truth from premises to conclusion by its logical form.",
            "If all insects have six legs, and spiders have eight legs, then spiders are not insects.",
            "The closure property states that performing an operation on elements of a set yields another element of that set.",
            "If all squares are rectangles with equal sides, and this rectangle has unequal sides, then it is not a square.",
            "In logic, a sound argument is both valid in form and has true premises in fact.",
            "If all rational numbers can be expressed as fractions, and pi cannot, then pi is not rational.",
            "The well-ordering principle states that every non-empty set of positive integers has a least element.",
            "If all equilateral triangles have equal angles, and this triangle is equilateral, then its angles are equal.",
            "A syllogism is a form of deductive reasoning with two premises and a conclusion.",
            "If all natural numbers are integers, and zero is a natural number, then zero is an integer.",
            "The density property of rational numbers states that between any two rationals there exists another rational.",
            "If all isosceles triangles have two equal sides, and this triangle has no equal sides, it is not isosceles.",
            "In formal systems, completeness means every true statement can be proven within the system.",
            "If all parallelograms have opposite sides parallel, and this quadrilateral does not, it is not a parallelogram.",
            "The Archimedean property states that for any real number there exists a larger natural number.",
            "If all conic sections are curves, and a parabola is a conic section, then a parabola is a curve.",
            "A proof by exhaustion verifies a statement by checking all possible cases individually.",
            "If all regular polygons have equal sides and angles, and this polygon does not, it is not regular.",
            "The fundamental theorem of arithmetic states that every integer greater than one has a unique prime factorization.",
            "If all rhombuses have equal sides, and this quadrilateral has unequal sides, then it is not a rhombus.",
            "In logic, the principle of explosion states that from a contradiction anything follows.",
            "If all trapezoids have at least one pair of parallel sides, and this shape has none, it is not a trapezoid.",
            "The triangle inequality states that the sum of any two sides must exceed the third side.",
            "If all kites have two pairs of adjacent equal sides, and this quadrilateral does not, it is not a kite.",
            "Godel incompleteness theorem shows that any sufficiently powerful formal system contains unprovable truths.",
            "If all cyclic quadrilaterals have opposite angles summing to one hundred eighty degrees, then this one does too.",
            "The intermediate value theorem guarantees that a continuous function takes every value between its endpoints.",
            "If all harmonic series diverge, and this series is harmonic, then this series diverges.",
            "The Bolzano-Weierstrass theorem states that every bounded sequence has a convergent subsequence.",
            "If all Cauchy sequences converge in complete spaces, and this space is complete, then they converge here.",
            "The mean value theorem relates the average rate of change to the instantaneous rate of change.",
            "If all continuous functions on closed intervals are bounded, and this function is continuous on a closed interval, it is bounded.",
            "The rank-nullity theorem relates the dimensions of the domain, kernel, and image of a linear map.",
            "If all compact sets in Euclidean space are closed and bounded, and this set is compact, then it is closed and bounded.",
            "The central limit theorem states that the sum of independent random variables approaches a normal distribution.",
            "If all orthogonal matrices preserve lengths, and this matrix is orthogonal, then it preserves lengths.",
            "The spectral theorem guarantees that every real symmetric matrix can be diagonalized by an orthogonal matrix.",
            "If all isometries preserve distances, and this transformation is an isometry, then it preserves distances.",
            "The Cayley-Hamilton theorem states that every square matrix satisfies its own characteristic equation.",
            "If all abelian groups have commutative operations, and this group is abelian, then its operation is commutative.",
            "The Heine-Borel theorem characterizes compact subsets of Euclidean space as closed and bounded sets.",
            "If all homeomorphisms are continuous bijections with continuous inverses, and this map is a homeomorphism, then it is.",
            "The divergence theorem relates the flux through a closed surface to the divergence within the enclosed volume.",
            "If all vector spaces have a basis, and this structure is a vector space, then it has a basis.",
            "The Stone-Weierstrass theorem states that continuous functions can be uniformly approximated by polynomials.",
            "If all Banach spaces are complete normed vector spaces, and this space is Banach, then it is complete.",
        ]
    },
    "emotional": {
        "expected": ["G6_limbic", "G5_dmn"],
        "texts": [
            "Her heart ached with a longing she could barely put into words.",
            "He felt a surge of triumph as years of effort finally paid off.",
            "The weight of grief settled over her like a heavy winter coat.",
            "Joy bubbled up from within as she watched her children play.",
            "A quiet contentment washed over him as he listened to the rain.",
            "Tears welled in her eyes as she read the heartfelt letter.",
            "He clenched his fists in frustration at the unfair treatment.",
            "A wave of nostalgia carried her back to simpler times.",
            "Pride swelled in his chest as he accepted the award.",
            "She trembled with fear as the footsteps grew closer.",
            "The warmth of gratitude filled her heart as strangers helped.",
            "He felt a deep sense of loss that nothing could fill.",
            "Anxiety gnawed at her stomach as the deadline approached.",
            "She beamed with delight at the unexpected surprise.",
            "A profound sadness settled over the room as the news spread.",
            "He felt the sting of betrayal from someone he trusted.",
            "Compassion overflowed as she witnessed the suffering of others.",
            "The thrill of adventure coursed through his veins.",
            "She felt a deep connection to the music that moved her to tears.",
            "Anger flared briefly before reason calmed his racing thoughts.",
            "A sense of wonder filled him as he gazed at the starry sky.",
            "She felt the bittersweet ache of saying goodbye to a dear friend.",
            "Relief washed over him when he heard the good news.",
            "The loneliness of the empty house echoed through every room.",
            "She felt a spark of hope despite the overwhelming odds.",
            "He was overwhelmed with guilt for words he could not take back.",
            "A gentle peace settled over her as she meditated at dawn.",
            "The excitement of discovery made her forget all her fatigue.",
            "She felt the sharp pang of jealousy but quickly let it go.",
            "A deep sense of belonging made him feel truly at home.",
            "The sorrow of parting lingered long after the train departed.",
            "He felt the intoxicating rush of falling in love for the first time.",
            "She was consumed by curiosity about the mysteries of the universe.",
            "A wave of embarrassment heated her cheeks as all eyes turned to her.",
            "He felt the heavy burden of responsibility on his shoulders.",
            "The serenity of the mountain lake calmed her troubled mind.",
            "She felt the fierce protectiveness of a mother for her child.",
            "A surge of adrenaline propelled him forward in the race.",
            "He felt the hollow ache of disappointment after the rejection.",
            "The joy of reunion brought tears to the entire family.",
            "She felt the quiet dignity of standing up for what was right.",
            "A storm of conflicting emotions raged within him.",
            "The tenderness in his voice made her heart flutter.",
            "She felt the crushing weight of expectations from her family.",
            "A spark of inspiration ignited her creative spirit.",
            "He felt the deep satisfaction of a job well done.",
            "The melancholy of autumn reminded her of passing time.",
            "She felt the fierce determination rising within her like fire.",
            "A sense of awe overwhelmed him as he stood before the ancient ruins.",
            "He felt the gentle comfort of a friend who truly understood.",
            "The bitterness of defeat tasted like ash in his mouth.",
            "She felt the exhilarating freedom of the open road.",
            "A deep sense of gratitude made her appreciate every small blessing.",
            "He felt the creeping dread of an approaching storm.",
            "The warmth of acceptance enveloped her like a soft blanket.",
            "She felt the sharp sting of criticism but used it to grow.",
            "A profound sense of purpose gave meaning to his struggles.",
            "He felt the tender ache of missing someone he loved dearly.",
            "The rush of accomplishment fueled her desire to achieve more.",
            "She felt the quiet strength that comes from surviving hardship.",
            "A wave of empathy washed over him as he heard her story.",
            "He felt the electric thrill of stepping onto the stage.",
            "The deep sorrow of loss gradually transformed into cherished memory.",
            "She felt the fierce loyalty that bound her to her closest friends.",
            "A sense of liberation freed her from years of self-doubt.",
            "He felt the gentle pull of homesickness while traveling abroad.",
            "The radiant happiness of the moment made everything worthwhile.",
            "She felt the heavy toll of sleepless nights and endless worry.",
            "A spark of rebellion ignited against the unjust rules.",
            "He felt the profound stillness of complete acceptance.",
            "The bittersweet taste of nostalgia made her smile through tears.",
            "She felt the fierce determination to prove everyone wrong.",
            "A deep sense of wonder filled him as he held his newborn child.",
            "The quiet despair of unfulfilled dreams haunted his thoughts.",
            "She felt the warm glow of recognition from her peers.",
            "He felt the sharp edge of regret for paths not taken.",
            "The overwhelming love she felt for her pet brought her to tears.",
            "A sense of anticipation built as the moment of truth approached.",
            "She felt the crushing loneliness of being misunderstood.",
            "He felt the gentle reassurance of knowing he was not alone.",
            "The fierce joy of victory made all the sacrifice worthwhile.",
            "A deep sense of peace settled over her troubled heart.",
            "He felt the burning passion that drove him to create.",
            "The tender vulnerability of opening up frightened yet freed her.",
            "A wave of inspiration swept through her as the solution appeared.",
            "She felt the heavy responsibility of leadership in crisis.",
            "He felt the quiet pride of watching his student succeed.",
            "The profound emptiness of loss left a void nothing could fill.",
            "A spark of mischief danced in her eyes as she planned the surprise.",
            "She felt the deep resonance of truth in his honest words.",
            "He felt the fierce protectiveness of standing up for the weak.",
            "The gentle melancholy of a fading sunset touched her soul.",
            "A surge of confidence replaced her lingering self-doubt.",
            "She felt the warm embrace of community after years of isolation.",
            "He felt the sharp clarity of purpose that comes with age.",
            "The overwhelming gratitude for life itself brought him to his knees.",
            "A deep sense of injustice fueled her fight for change.",
            "She felt the quiet contentment of a life well lived.",
            "He felt the fierce determination to never give up hope.",
            "The tender beauty of the moment made time seem to stand still.",
            "A wave of compassion softened her hardened heart.",
            "She felt the electric excitement of new possibilities unfolding.",
            "He felt the profound connection between all living things.",
            "The gentle sadness of letting go was mixed with gratitude for what was.",
        ]
    },
    "factual": {
        "expected": ["G4_pfc", "G7_sensory"],
        "texts": [
            "The speed of light in vacuum is exactly 299,792,458 meters per second.",
            "Human DNA contains approximately three billion base pairs of genetic information.",
            "The Earth atmosphere is composed primarily of nitrogen and oxygen.",
            "Water has its maximum density at four degrees Celsius.",
            "The human genome contains roughly twenty thousand protein-coding genes.",
            "The planet Jupiter has at least ninety-five known moons orbiting it.",
            "Photosynthesis converts carbon dioxide and water into glucose using sunlight.",
            "The Great Wall of China stretches over thirteen thousand miles in total length.",
            "Sound travels through air at approximately 343 meters per second at room temperature.",
            "The human body contains approximately 206 bones in the adult skeleton.",
            "The periodic table currently contains 118 confirmed chemical elements.",
            "The Pacific Ocean covers more area than all land masses combined.",
            "A light-year is approximately 9.46 trillion kilometers in distance.",
            "The human brain consumes about twenty percent of the body total energy.",
            "Mount Everest stands at 8,848.86 meters above sea level.",
            "The chemical formula for glucose is C6H12O6 with six carbon atoms.",
            "The Earth rotates on its axis once every 23 hours and 56 minutes.",
            "The human heart beats approximately 100,000 times per day.",
            "The Amazon River discharges more water than the next seven largest rivers combined.",
            "The atomic number of carbon is six, meaning it has six protons.",
            "The Sahara Desert covers approximately 9.2 million square kilometers.",
            "The human eye can distinguish approximately 10 million different colors.",
            "The speed of sound in water is approximately 1,480 meters per second.",
            "The Milky Way galaxy contains between 100 and 400 billion stars.",
            "The boiling point of water decreases at higher altitudes due to lower pressure.",
            "The human skeleton is replaced entirely approximately every 10 years.",
            "The distance from Earth to the Sun is approximately 150 million kilometers.",
            "The chemical element gold has the atomic number 79 on the periodic table.",
            "The human liver performs over 500 known functions including detoxification.",
            "The Mariana Trench is the deepest known point in the ocean at 11,034 meters.",
            "The Earth magnetic field protects the planet from solar wind radiation.",
            "The human nervous system contains approximately 86 billion neurons.",
            "The wavelength of visible light ranges from 380 to 750 nanometers.",
            "The Great Barrier Reef is the largest living structure on Earth.",
            "The human body contains approximately 37.2 trillion cells.",
            "The planet Saturn has a density lower than that of water.",
            "The chemical bond between two oxygen atoms in O2 is a double covalent bond.",
            "The human digestive tract is approximately nine meters long in adults.",
            "The age of the universe is estimated at 13.8 billion years.",
            "The element helium was first discovered in the solar spectrum before Earth.",
            "The human skin is the largest organ covering approximately 1.5 to 2 square meters.",
            "The speed of light is approximately 300,000 kilometers per second in vacuum.",
            "The planet Venus has surface temperatures hot enough to melt lead.",
            "The human red blood cell has a lifespan of approximately 120 days.",
            "The chemical element iron is the most abundant element in the Earth core.",
            "The human fingerprint pattern is unique to each individual including identical twins.",
            "The planet Neptune has the strongest sustained winds of any planet at 2,100 km/h.",
            "The human cornea is the only tissue in the body without a blood supply.",
            "The chemical reaction between sodium and water produces hydrogen gas and heat.",
            "The human ear can detect frequencies ranging from 20 to 20,000 hertz.",
            "The planet Mercury has no atmosphere and extreme temperature variations.",
            "The human pancreas produces both digestive enzymes and the hormone insulin.",
            "The chemical element uranium has an atomic number of 92 and is radioactive.",
            "The human retina contains approximately 120 million rod cells for low-light vision.",
            "The planet Mars has the tallest volcano in the solar system, Olympus Mons.",
            "The human stomach produces a new layer of mucus every two weeks.",
            "The chemical compound sodium chloride is commonly known as table salt.",
            "The human spinal cord contains approximately 31 pairs of spinal nerves.",
            "The planet Pluto was reclassified as a dwarf planet in 2006 by the IAU.",
            "The human body produces approximately 1.5 liters of saliva per day.",
            "The chemical element fluorine is the most electronegative element on the periodic table.",
            "The human vestibular system in the inner ear maintains balance and spatial orientation.",
            "The planet Saturn has the lowest density of any planet at 0.687 grams per cubic centimeter.",
            "The human immune system can produce billions of different antibodies.",
            "The chemical process of fermentation converts sugars into alcohol and carbon dioxide.",
            "The human pineal gland produces melatonin which regulates sleep-wake cycles.",
            "The planet Uranus rotates on its side with an axial tilt of 98 degrees.",
            "The human body loses approximately 600 milliliters of water daily through respiration.",
            "The chemical element neon produces a distinctive red-orange glow in discharge tubes.",
            "The human thymus gland is most active during childhood and shrinks after puberty.",
            "The planet Venus rotates in the opposite direction to most other planets.",
            "The human body contains approximately 5 liters of blood circulating continuously.",
            "The chemical element argon makes up nearly one percent of the Earth atmosphere.",
            "The human hypothalamus regulates body temperature, hunger, and thirst.",
            "The planet Jupiter has the shortest day of any planet at about 10 hours.",
            "The human body produces approximately 250 million new red blood cells per second.",
            "The chemical element silicon is the second most abundant element in the Earth crust.",
            "The human cerebellum contains more neurons than the rest of the brain combined.",
            "The planet Earth is the densest planet in the solar system at 5.51 grams per cubic centimeter.",
            "The human body contains approximately 60 percent water by weight in adults.",
            "The chemical element potassium is essential for nerve function and muscle contraction.",
            "The human olfactory system can distinguish approximately one trillion different odors.",
            "The planet Mercury has the most eccentric orbit of any planet in the solar system.",
            "The human body produces approximately 1.5 to 2 liters of gastric juice daily.",
            "The chemical element calcium is the most abundant mineral in the human body.",
            "The human blood-brain barrier protects the brain from harmful substances in the blood.",
            "The planet Neptune takes 165 Earth years to complete one orbit around the Sun.",
            "The human body contains approximately 650 skeletal muscles that enable movement.",
            "The chemical element zinc is essential for immune function and wound healing.",
            "The human circadian rhythm is regulated by the suprachiasmatic nucleus in the brain.",
            "The planet Mars has two small moons named Phobos and Deimos.",
            "The human body produces approximately 300 billion new cells every day.",
            "The chemical element magnesium is required for over 300 enzymatic reactions.",
            "The human body contains approximately 100,000 miles of blood vessels.",
            "The chemical element copper is an excellent conductor of electricity and heat.",
            "The human body loses approximately 400 million skin cells every day.",
            "The chemical element iodine is essential for thyroid hormone production.",
            "The human body contains approximately 100,000 hairs on the scalp.",
            "The chemical element selenium acts as an antioxidant protecting cells from damage.",
            "The human body produces approximately 1 to 1.5 liters of tears annually.",
            "The chemical element manganese is important for bone formation and metabolism.",
            "The human body contains approximately 2.5 million sweat glands for temperature regulation.",
            "The chemical element chromium helps regulate blood sugar levels in the body.",
            "The human body produces approximately 0.5 to 1 liter of bile daily.",
            "The chemical element molybdenum is a cofactor for several important enzymes.",
            "The human body contains approximately 32 permanent teeth in the adult mouth.",
            "The chemical element cobalt is a component of vitamin B12 essential for nerve function.",
        ]
    },
    "abstract": {
        "expected": ["G5_dmn", "G3_tpj"],
        "texts": [
            "If reality is fundamentally mathematical, then consciousness might be a computational process.",
            "The boundary between self and other may be more permeable than we imagine.",
            "Perhaps meaning emerges not from individual symbols but from their relationships.",
            "Time might be nothing more than a convenient way to order our experiences.",
            "The question of whether machines can think may itself be the wrong question.",
            "What if the universe is a simulation and we are characters in someone else dream?",
            "If consciousness emerges from complexity, at what point does a system become aware?",
            "Perhaps free will is an illusion created by the brain predictive mechanisms.",
            "The nature of reality may be fundamentally different from our perception of it.",
            "What is the relationship between language and thought, and does one shape the other?",
            "If we could upload our minds to computers, would we still be ourselves?",
            "The concept of infinity challenges our ability to comprehend the universe.",
            "Can we ever truly know another person subjective experience?",
            "If every choice creates a branching universe, how many versions of us exist?",
            "The distinction between observer and observed may be an artifact of perception.",
            "What does it mean to exist if existence itself cannot be proven?",
            "If memories define identity, who are we when we forget?",
            "The paradox of self-reference suggests that any complete system must be incomplete.",
            "Perhaps the universe is not a thing but a process of becoming.",
            "If information is the fundamental substance of reality, what does it mean to know?",
            "The arrow of time may be an emergent property of increasing entropy.",
            "What if colors do not exist outside of the mind that perceives them?",
            "The boundary between dream and reality dissolves upon close examination.",
            "If mathematics describes the universe perfectly, is mathematics discovered or invented?",
            "The concept of nothingness may be the most profound philosophical puzzle.",
            "What if every moment contains the entirety of time within it?",
            "The observer effect suggests that consciousness shapes the reality it observes.",
            "If the self is an illusion, who is experiencing this illusion?",
            "Perhaps the universe is a self-similar fractal repeating at every scale.",
            "The distinction between mind and matter may be a false dichotomy.",
            "What if the laws of physics are not fixed but evolve over cosmic time?",
            "The nature of causality may be more complex than simple cause and effect.",
            "If consciousness is fundamental, then matter may be a manifestation of mind.",
            "The concept of identity over time challenges our notion of personal continuity.",
            "What if the multiverse contains every possible variation of every possible world?",
            "The relationship between the part and the whole may be the key to understanding reality.",
            "If knowledge requires certainty, can we truly know anything at all?",
            "The nature of beauty may lie in the tension between order and chaos.",
            "What if the universe is conscious and we are its way of knowing itself?",
            "The paradox of the heap suggests that vagueness is inherent in language.",
            "If time is an illusion, then all moments exist simultaneously.",
            "The distinction between natural and artificial may be meaningless at the fundamental level.",
            "What if the purpose of existence is simply to exist?",
            "The nature of truth may be contextual rather than absolute.",
            "If the mind creates reality, then reality is a shared hallucination.",
            "The concept of emergence suggests that wholes are greater than the sum of their parts.",
            "What if the universe is a single thought thinking itself?",
            "The boundary between the finite and the infinite may be an illusion of perspective.",
            "If perception shapes reality, then there are as many realities as there are perceivers.",
            "The nature of creativity may be the recombination of existing elements in novel ways.",
            "What if the self is not a thing but a pattern that persists through time?",
            "The paradox of tolerance suggests that unlimited tolerance leads to its own destruction.",
            "If the universe is deterministic, then choice is an elaborate form of necessity.",
            "The nature of understanding may be the ability to see connections between disparate ideas.",
            "What if consciousness is not produced by the brain but filtered through it?",
            "The concept of progress may be a narrative we impose on the chaos of change.",
            "If language limits thought, then expanding language expands the boundaries of thought.",
            "The nature of wisdom may be knowing the difference between what can and cannot be changed.",
            "What if the universe is a story telling itself to itself?",
            "The distinction between subject and object may be a useful fiction rather than a fact.",
            "If meaning is constructed, then every individual is the author of their own meaning.",
            "The nature of freedom may be the recognition of necessity rather than escape from it.",
            "What if the past does not exist except as memory and the future only as imagination?",
            "The concept of perfection may be the enemy of the good.",
            "If the mind is a mirror, then reality is what it reflects and what it distorts.",
            "The nature of empathy may be the ability to simulate another mind within ones own.",
            "What if the universe is a hologram and three-dimensional space is an illusion?",
            "The paradox of choice suggests that more options can lead to less satisfaction.",
            "If truth is relative, then the statement truth is relative is itself relative.",
            "The nature of intuition may be pattern recognition operating below the level of consciousness.",
            "What if the self is a narrative constructed by the brain to create coherence?",
            "The concept of justice may be an approximation of balance in an unbalanced world.",
            "If the universe is infinite, then every possible configuration of matter must exist somewhere.",
            "The nature of courage may be acting despite fear rather than without it.",
            "What if the distinction between real and virtual will eventually become meaningless?",
            "The paradox of fiction suggests that we experience real emotions for unreal events.",
            "If consciousness is a spectrum, then there may be degrees of awareness in all matter.",
            "The nature of love may be the recognition of oneself in another.",
            "What if the universe is a dream dreamed by a cosmic consciousness?",
            "The concept of reality may be the set of constraints within which imagination operates.",
            "If knowledge is power, then ignorance may be a form of freedom.",
            "The nature of creativity may be the ability to see what others overlook.",
            "What if the universe is not made of matter or energy but of information?",
            "The paradox of tolerance suggests that a tolerant society must be intolerant of intolerance.",
            "If the mind is the measure of all things, then the measure itself must be measured.",
            "The nature of understanding may be the ability to hold multiple perspectives simultaneously.",
            "What if consciousness is the universe observing itself?",
            "The nature of identity may be more fluid than we typically assume.",
            "If every observation changes the observed, then pure objectivity is impossible.",
            "The concept of progress in science may be asymptotic, approaching but never reaching truth.",
            "What if the universe is a mathematical structure and we are self-aware substructures?",
            "The paradox of hedonism suggests that pursuing happiness directly makes it elusive.",
            "If every explanation requires a further explanation, then understanding has no foundation.",
            "The nature of art may be the communication of the incommunicable.",
            "What if the universe is a computation and the laws of physics are its algorithm?",
            "The concept of identity may be a useful simplification of constant change.",
            "If the observer creates the observed, then reality is a collaborative construction.",
            "The nature of insight may be the sudden reorganization of existing knowledge.",
            "What if the universe is a single entity experiencing itself through countless perspectives?",
            "The paradox of analysis suggests that any analysis either repeats or distorts its subject.",
            "If the self is a process rather than a substance, then identity is a verb not a noun.",
            "The nature of wonder may be the recognition of mystery at the heart of the familiar.",
            "What if the universe is a dream dreamed by a cosmic consciousness?",
            "The concept of reality may be the set of constraints within which imagination operates.",
            "If knowledge is power, then ignorance may be a form of freedom.",
        ]
    },
    "spatial": {
        "expected": ["G7_sensory", "G9_premotor"],
        "texts": [
            "The ancient temple stood at the center of a vast circular plaza.",
            "Rivers carved deep canyons through layers of sedimentary rock over millennia.",
            "The spiral galaxy rotated slowly, its arms stretching across light-years of space.",
            "Mountains rose in jagged peaks against the horizon like frozen waves.",
            "The labyrinth wound inward through corridors that seemed to shift and change.",
            "The cathedral dome soared upward in a perfect hemisphere above the nave.",
            "Valleys stretched between parallel mountain ranges like green ribbons.",
            "The spiral staircase wound upward around a central stone pillar.",
            "The coastline curved in a sweeping arc from the bay to the headland.",
            "The city grid extended in perfect rectangular blocks to the horizon.",
            "The canyon walls rose vertically on both sides of the narrow river.",
            "The amphitheater was carved in a semicircle into the hillside.",
            "The archipelago formed a crescent shape across the turquoise waters.",
            "The suspension bridge spanned the wide gorge between two cliffs.",
            "The terraced fields climbed the hillside in concentric rings.",
            "The observatory dome rotated on its axis to track the stars.",
            "The river delta branched into dozens of channels before reaching the sea.",
            "The fortress walls formed a perfect pentagon around the central keep.",
            "The dunes shifted in undulating waves across the vast desert.",
            "The tunnel curved gently through the mountain before emerging into sunlight.",
            "The orbital path of the satellite traced an ellipse around the Earth.",
            "The plaza was surrounded by colonnades forming a perfect rectangle.",
            "The fjord cut deeply into the coastline between towering cliffs.",
            "The greenhouse was constructed in a geodesic dome of triangular panels.",
            "The railway tracks curved around the base of the mountain in a wide arc.",
            "The atoll formed a ring of coral islands surrounding a central lagoon.",
            "The aqueduct arched across the valley on a series of stone pillars.",
            "The crater lake sat perfectly circular within the volcanic caldera.",
            "The highway spiraled up the mountainside in a series of switchbacks.",
            "The courtyard was enclosed by four wings forming a square around a garden.",
            "The glacier flowed slowly down the valley carving a U-shaped trough.",
            "The pagoda rose in tiers, each level smaller than the one below.",
            "The peninsula jutted into the sea like a finger pointing toward the horizon.",
            "The rotunda was topped by a dome with an oculus at its center.",
            "The ravine split the plateau in two with sheer walls on either side.",
            "The satellite dish pointed at a precise angle toward the geostationary orbit.",
            "The escarpment formed a dramatic cliff edge overlooking the coastal plain.",
            "The viaduct arched over the river valley on a series of graceful curves.",
            "The mesa rose flat-topped from the surrounding desert like a table.",
            "The cloister walk formed a square around the central garden courtyard.",
            "The isthmus connected two larger land masses with a narrow strip of land.",
            "The ziggurat rose in stepped terraces toward the sky in a square pyramid.",
            "The strait separated two seas with a narrow channel of turbulent water.",
            "The colonnade stretched in a straight line along the front of the temple.",
            "The oasis sat in a depression surrounded by towering sand dunes.",
            "The buttress arched outward from the cathedral wall to support the vaulted ceiling.",
            "The plateau extended in a vast flat expanse above the surrounding lowlands.",
            "The narrows compressed the wide river into a tight channel between rock walls.",
            "The tower rose in a tapering cone from a wide circular base.",
            "The basin collected water from the surrounding hills in a natural bowl shape.",
            "The causeway stretched across the marsh on a raised straight path.",
            "The pinnacle rose from the cave floor in a slender column of stone.",
            "The terrace stepped down the hillside in a series of flat levels.",
            "The channel wound between the islands in a meandering serpentine path.",
            "The dome of the planetarium projected stars onto the curved ceiling.",
            "The ridge ran along the mountaintop like the spine of a great beast.",
            "The grotto opened into a cavern with stalactites hanging from the ceiling.",
            "The promontory extended into the lake with steep cliffs on three sides.",
            "The vault of the ceiling arched overhead in a series of intersecting curves.",
            "The shoal stretched beneath the surface of the shallow water like a submerged plain.",
            "The parapet ran along the top of the castle wall with crenellations at regular intervals.",
            "The trough of the valley was filled with mist that swirled around the slopes.",
            "The spire rose to a needle point above the Gothic cathedral roof.",
            "The shelf of rock projected from the cliff face like a natural balcony.",
            "The moat surrounded the castle in a wide water-filled ditch.",
            "The cornice projected from the top of the wall in an ornamental ledge.",
            "The reef stretched parallel to the shore beneath the clear shallow water.",
            "The balcony overlooked the square from the second story of the building.",
            "The strait connected the inland sea to the open ocean through a narrow passage.",
            "The gable formed a triangular wall at each end of the pitched roof.",
            "The cay rose as a small sandy island from the surrounding coral reef.",
            "The transept crossed the nave of the church forming a cruciform floor plan.",
            "The scarp formed a steep slope at the edge of the elevated plain.",
            "The portico extended from the front of the building with columns supporting a pediment.",
            "The bay curved inward from the coast creating a sheltered harbor.",
            "The ledge ran along the cliff face at a constant elevation.",
            "The atrium opened to the sky at the center of the Roman house.",
            "The headland projected into the sea with waves crashing against its base.",
            "The niche was carved into the wall to hold a statue of the saint.",
            "The cove formed a small sheltered inlet with a pebble beach.",
            "The arcade ran along the side of the building with a series of arches.",
            "The bluff rose steeply from the riverbank offering a view of the valley.",
            "The alcove provided a recessed space for reading beside the main hall.",
            "The reef broke the surface of the water in a ring of white foam.",
            "The cornice decorated the top of the building with intricate carved patterns.",
            "The dell was a small secluded valley surrounded by dense woodland.",
            "The pediment crowned the front of the temple with a triangular sculpted panel.",
            "The gorge cut through the mountains with walls too steep to climb.",
            "The colonnade supported the roof with a row of evenly spaced columns.",
            "The knoll rose as a small rounded hill above the surrounding meadow.",
            "The frieze ran along the upper part of the wall with decorative reliefs.",
            "The hollow in the hillside provided shelter from the prevailing wind.",
            "The archway framed the entrance to the garden with a semicircular opening.",
            "The plateau was bounded on all sides by steep escarpments.",
            "The balustrade lined the edge of the terrace with ornamental railings.",
            "The depression in the landscape collected rainwater to form a seasonal pond.",
            "The portico provided a covered entrance with columns supporting an overhanging roof.",
            "The watershed divided the drainage basins of two major river systems.",
            "The gallery ran along the upper level of the hall overlooking the floor below.",
            "The promontory offered a commanding view of the surrounding countryside.",
            "The cul-de-sac ended in a circular turnaround surrounded by houses.",
        ]
    },
    "social": {
        "expected": ["G3_tpj", "G4_pfc"],
        "texts": [
            "She could tell from his hesitation that he was hiding something important.",
            "The mediator carefully balanced the competing interests of both parties.",
            "He sensed the unspoken tension in the room before anyone said a word.",
            "The teacher noticed which students were struggling and adjusted her approach.",
            "They reached an understanding without ever explicitly discussing the issue.",
            "She recognized the subtle hint of sarcasm in his seemingly complimentary remark.",
            "The diplomat navigated the delicate negotiations with practiced skill.",
            "He understood that her silence meant disagreement rather than agreement.",
            "The manager read the room and shifted the meeting agenda accordingly.",
            "She perceived the underlying motive behind his generous offer.",
            "The counselor picked up on the client unspoken fears about the future.",
            "He realized that her laughter was masking genuine discomfort.",
            "The negotiator found common ground between two seemingly irreconcilable positions.",
            "She detected the faint note of jealousy beneath his congratulations.",
            "The leader sensed the growing unrest among the team members.",
            "He interpreted her body language as a signal to change the subject.",
            "The therapist recognized the defense mechanism behind the patient humor.",
            "She understood that his criticism was really a plea for attention.",
            "The judge weighed the credibility of each witness testimony carefully.",
            "He sensed that the group was divided despite their outward agreement.",
            "The parent recognized the cry as hunger rather than discomfort.",
            "She perceived the power dynamics at play in the committee meeting.",
            "The friend noticed the forced smile and asked if everything was okay.",
            "He understood that the invitation was obligatory rather than genuine.",
            "The coach read the opposing team strategy and adjusted the game plan.",
            "She detected the subtle shift in tone that indicated his true feelings.",
            "The interviewer sensed the candidate nervousness and put them at ease.",
            "He recognized the cultural reference that everyone else in the room missed.",
            "The social worker understood the family dynamics from a single home visit.",
            "She perceived the unspoken hierarchy within the organization.",
            "The host noticed the guest discomfort and changed the conversation topic.",
            "He understood that the delay was intentional rather than accidental.",
            "The peer mediator helped the students find a mutually acceptable solution.",
            "She detected the genuine enthusiasm beneath his professional demeanor.",
            "The community organizer sensed the shifting priorities of the neighborhood.",
            "He recognized that her question was really a statement in disguise.",
            "The group facilitator noticed who was dominating and who was withdrawing.",
            "She understood that the compliment carried an implicit expectation.",
            "The mentor recognized the signs of burnout in his protege.",
            "He perceived the underlying anxiety behind her confident presentation.",
            "The team leader sensed the lack of trust and addressed it directly.",
            "She detected the subtle manipulation in his seemingly reasonable argument.",
            "The friend understood that the canceled plans were really about something deeper.",
            "He recognized the cultural faux pas immediately and apologized gracefully.",
            "The teacher perceived the bullying dynamic that was invisible to others.",
            "She understood that his anger was really fear in disguise.",
            "The manager noticed the pattern of exclusion and intervened.",
            "He sensed that the consensus was superficial and invited dissenting views.",
            "The counselor recognized the transference in the therapeutic relationship.",
            "She perceived the unspoken rules that governed the social group.",
            "The leader understood that resistance to change was really about loss of control.",
            "He detected the genuine concern beneath her critical feedback.",
            "The negotiator sensed that the other party was bluffing about their bottom line.",
            "She recognized the microaggression and addressed it constructively.",
            "The friend understood that the silence meant something was deeply wrong.",
            "He perceived the social anxiety that made networking events so difficult.",
            "The mediator recognized when to push and when to give space.",
            "She understood that the gossip was really about insecurity.",
            "The coach perceived the team chemistry issues that statistics could not show.",
            "He detected the subtle power play in the committee discussion.",
            "The therapist recognized the attachment pattern from the first session.",
            "She sensed that the conflict was really about unmet needs.",
            "The manager understood that the productivity issue was really a motivation problem.",
            "He perceived the social exclusion that was happening in subtle ways.",
            "The teacher recognized the gifted student who was hiding their abilities.",
            "She understood that the resistance was really about fear of failure.",
            "The leader sensed the moral injury affecting the team after the difficult decision.",
            "He detected the genuine curiosity beneath her challenging questions.",
            "The friend recognized the cry for help disguised as casual conversation.",
            "She perceived the systemic bias that was affecting hiring decisions.",
            "The counselor understood that the presenting problem was not the real problem.",
            "He sensed that the agreement was fragile and needed reinforcement.",
            "The mediator recognized the emotional triggers that were derailing the discussion.",
            "She understood that the criticism was really a projection of self-doubt.",
            "The team leader perceived the informal leadership that existed outside the hierarchy.",
            "He detected the cultural misunderstanding that was causing the conflict.",
            "The social worker recognized the resilience beneath the surface of crisis.",
            "She sensed that the group needed time to process before making a decision.",
            "The manager understood that the turnover was really about leadership style.",
            "He perceived the unspoken grief that was affecting the workplace culture.",
            "The teacher recognized the trauma response that looked like defiance.",
            "She understood that the competition was really about self-worth.",
            "The leader sensed the collective burnout before anyone admitted it.",
            "He detected the genuine breakthrough beneath the patient resistance.",
            "The friend recognized the boundary violation and addressed it with compassion.",
            "She perceived the intergenerational patterns that were repeating in the family.",
            "The negotiator understood that the real issue was about dignity not dollars.",
            "He sensed that the resistance to feedback was really about shame.",
            "The counselor recognized the strength in the vulnerability the client showed.",
            "She understood that the conflict was really about different values.",
            "The team leader perceived the psychological safety that was missing.",
            "He detected the authentic connection beneath the professional formality.",
            "The mediator recognized when the parties were ready to move toward resolution.",
            "She sensed that the organizational culture needed healing before it could grow.",
            "The manager understood that the communication breakdown was really about trust.",
            "He perceived the collective wisdom that emerged when everyone was heard.",
            "The teacher recognized the potential in the student everyone else had given up on.",
            "She understood that the social dynamic was more complex than it appeared.",
            "The leader sensed the moment when the group shifted from individual to collective thinking.",
        ]
    },
    "motor": {
        "expected": ["G9_premotor", "G1_broca"],
        "texts": [
            "The potter shaped the clay with practiced hands on the spinning wheel.",
            "She caught the falling glass before it hit the ground with lightning reflexes.",
            "The carpenter measured twice and cut the board with a single smooth stroke.",
            "He juggled three balls in a continuous rhythmic pattern without dropping one.",
            "The calligrapher brush moved across the paper in fluid graceful strokes.",
            "The dancer pirouetted across the stage with effortless precision.",
            "She threaded the needle with steady hands despite the dim light.",
            "The blacksmith hammered the red-hot iron into the shape of a blade.",
            "He balanced on the tightrope with arms outstretched for stability.",
            "The surgeon sutured the wound with precise controlled movements.",
            "She served the tennis ball with a powerful overhand motion.",
            "The pianist fingers flew across the keys in a blur of motion.",
            "He vaulted over the hurdle with practiced athletic form.",
            "The sculptor chiseled the marble with deliberate measured strikes.",
            "She dribbled the basketball through the defenders with quick agile steps.",
            "The archer drew the bowstring back and released with perfect aim.",
            "He weaved through the crowd with quick sidesteps and pivots.",
            "The gymnast executed a flawless backflip from the balance beam.",
            "She kneaded the dough with strong rhythmic pressing and folding.",
            "The drummer maintained a complex polyrhythm with all four limbs.",
            "He swung the bat and connected with the ball at the perfect moment.",
            "The typist fingers moved across the keyboard at incredible speed.",
            "She performed a perfect handstand against the wall.",
            "The fencer lunged forward with a lightning-fast thrust of the blade.",
            "He rowed the boat with smooth synchronized strokes.",
            "The chef chopped vegetables with rapid precise knife work.",
            "She performed a cartwheel followed by a back handspring.",
            "The boxer dodged the punch and countered with a swift jab.",
            "He climbed the rock face using only his hands and feet.",
            "The seamstress guided the fabric through the sewing machine.",
            "She executed a perfect dive from the ten-meter platform.",
            "The mechanic tightened the bolts with a torque wrench to exact specifications.",
            "He performed a series of rapid push-ups with perfect form.",
            "The violinist drew the bow across the strings with controlled pressure.",
            "She performed a roundhouse kick with speed and accuracy.",
            "The welder guided the torch along the seam with steady hands.",
            "He sprinted the final hundred meters with powerful leg drive.",
            "The baker shaped the dough into perfect braided loaves.",
            "She performed a series of yoga poses with fluid transitions.",
            "The golfer swung the club in a smooth arc striking the ball cleanly.",
            "He performed pull-ups with controlled movement and full range of motion.",
            "The glassblower rotated the molten glass at the end of the blowpipe.",
            "She performed a perfect split leap across the dance floor.",
            "The cyclist pedaled uphill standing on the pedals with powerful strokes.",
            "He performed a series of rapid-fire punches on the heavy bag.",
            "The jeweler set the tiny gemstone into the ring with precision tweezers.",
            "She performed a flawless parallel park in a single smooth motion.",
            "The swimmer executed a perfect flip turn at the wall.",
            "He performed a series of complex skateboard tricks on the halfpipe.",
            "The mason laid each brick with mortar in perfectly level rows.",
            "She performed a series of rapid alternating hand movements.",
            "The baseball pitcher wound up and threw a blazing fastball.",
            "He performed a series of controlled squats with a heavy barbell.",
            "The watchmaker assembled the tiny gears with precision tweezers.",
            "She performed a series of rapid finger exercises on the piano.",
            "The skateboarder ollied over the gap and landed smoothly.",
            "He performed a series of controlled deadlifts with proper form.",
            "The painter applied brushstrokes in long sweeping motions across the canvas.",
            "She performed a series of rapid finger taps in a specific sequence.",
            "The soccer player struck the ball with the inside of her foot.",
            "He performed a series of controlled lunges alternating legs.",
            "The potter trimmed the base of the vase with a sharp wire tool.",
            "She performed a series of rapid eye-hand coordination tasks.",
            "The martial artist executed a spinning kick with perfect balance.",
            "He performed a series of controlled planks engaging his core.",
            "The embroiderer stitched intricate patterns with tiny precise needle movements.",
            "She performed a series of rapid lateral shuffles across the court.",
            "The rock climber reached for the next hold with calculated precision.",
            "He performed a series of controlled overhead presses with dumbbells.",
            "The chef flipped the pancake high into the air and caught it perfectly.",
            "She performed a series of rapid finger exercises on the piano.",
            "The skateboarder ollied over the gap and landed smoothly.",
            "He performed a series of controlled bicep curls with slow eccentric movement.",
            "The tailor pinned the fabric with quick precise movements of her fingers.",
            "She performed a series of rapid footwork patterns in the boxing ring.",
            "The drummer executed a complex drum roll with alternating hand strokes.",
            "He performed a series of controlled Russian twists engaging his obliques.",
            "The archer released three arrows in rapid succession all hitting the bullseye.",
            "She performed a series of rapid hand-eye coordination drills.",
            "The gymnast performed a series of rapid tumbling passes down the floor.",
            "He performed a series of controlled calf raises on the edge of a step.",
            "The chef plated the dish with precise artistic placement of each element.",
            "She performed a series of rapid alternating finger-to-thumb touches.",
            "The tennis player executed a perfect topspin forehand down the line.",
            "He performed a series of controlled hip thrusts with a barbell.",
            "The carpenter planed the wood surface with long smooth forward strokes.",
            "She performed a series of rapid reactive agility drills.",
            "The figure skater landed a triple axel with one foot on the ice.",
            "He performed a series of controlled bird-dog exercises for core stability.",
            "The woodworker carved the decorative pattern with a sharp gouge.",
            "She performed a series of rapid change-of-direction sprints.",
            "The volleyball player spiked the ball with a powerful jump and arm swing.",
            "He performed a series of controlled single-leg balance exercises.",
            "The baker scored the bread dough with a razor in a decorative pattern.",
            "She performed a series of rapid reactive catching drills.",
            "The martial artist blocked the strike and countered with a palm strike.",
            "He performed a series of controlled glute bridges with a pause at the top.",
            "The potter centered the clay on the wheel with firm steady pressure.",
            "She performed a series of rapid reactive stepping patterns.",
            "The hockey player deked around the defender and scored on the breakaway.",
            "He performed a series of controlled single-arm rows with a dumbbell.",
            "The chef flambed the dish with a controlled burst of flame.",
            "She performed a series of rapid reactive balance challenges.",
        ]
    },
    "memory": {
        "expected": ["G5_dmn", "G6_limbic"],
        "texts": [
            "The smell of old books instantly transported him back to the library of his youth.",
            "Fragments of the conversation replayed in her mind long after the meeting ended.",
            "The photograph captured a moment that time had otherwise erased from memory.",
            "He could still hear his grandfather voice telling stories by the fire.",
            "The melody triggered a cascade of forgotten summer afternoons and childhood games.",
            "The taste of her grandmother recipe brought back vivid memories of Sunday dinners.",
            "She remembered the exact spot where they first met under the old oak tree.",
            "The faded ticket stub reminded him of the concert that changed his life.",
            "He recalled the feeling of his first day at school with perfect clarity.",
            "The scent of jasmine carried her back to the garden of her childhood home.",
            "She remembered the sound of rain on the tin roof of the old farmhouse.",
            "The worn teddy bear held memories of countless bedtime stories and comfort.",
            "He recalled the warmth of the sun on that perfect summer afternoon.",
            "The old diary revealed thoughts and feelings she had long forgotten.",
            "She remembered the taste of the first meal she cooked for her family.",
            "The sound of the school bell triggered memories of recess and friendship.",
            "He recalled the exact words his mentor said that changed his career path.",
            "The weathered map reminded her of the road trip across the country.",
            "She remembered the feeling of holding her newborn child for the first time.",
            "The old song on the radio brought back memories of high school dances.",
            "He recalled the sight of the ocean for the very first time as a child.",
            "The pressed flower in the book marked a day she would never forget.",
            "She remembered the sound of her mother singing her to sleep.",
            "The old watch still ticked, marking time from a life long past.",
            "He recalled the feeling of accomplishment after finishing his first marathon.",
            "The childhood home stood in her memory exactly as she had left it.",
            "She remembered the taste of snowflakes melting on her tongue as a child.",
            "The old letter brought tears as she reread words from a dear friend.",
            "He recalled the sound of crickets on warm summer evenings in the country.",
            "The souvenir from the trip sat on the shelf as a tangible memory.",
            "She remembered the feeling of grass between her toes on the first day of spring.",
            "The old movie transported her back to the era of her grandparents youth.",
            "He recalled the smell of his father workshop filled with sawdust and oil.",
            "The anniversary date marked a moment that had shaped the course of their lives.",
            "She remembered the sound of waves crashing on the shore of their vacation.",
            "The old recipe card bore stains and notes from years of cooking.",
            "He recalled the feeling of snow crunching under his boots on winter mornings.",
            "The childhood toy still sat in the attic, preserved with care.",
            "She remembered the sight of the northern lights dancing across the arctic sky.",
            "The old journal entry described a day that seemed like it belonged to someone else.",
            "He recalled the sound of his dog greeting him at the door every evening.",
            "The faded painting reminded her of the art class that sparked her passion.",
            "She remembered the feeling of the first warm day after a long winter.",
            "The old telephone number was still memorized though it had not been used in years.",
            "He recalled the taste of his first cup of coffee on a cold morning.",
            "The childhood photograph showed a moment of pure unselfconscious joy.",
            "She remembered the sound of the ice cream truck approaching on summer days.",
            "The old medal in the drawer represented years of dedication and practice.",
            "He recalled the feeling of sand between his toes on a tropical beach.",
            "The recipe passed down through generations carried the taste of family history.",
            "She remembered the sight of her graduation cap flying into the air.",
            "The old key no longer fit any lock but was kept for sentimental reasons.",
            "He recalled the sound of his children laughter echoing through the house.",
            "The dried bouquet from a special occasion still held its shape and color.",
            "She remembered the feeling of riding a bicycle for the first time without help.",
            "The old postcard from a distant place sparked memories of adventure.",
            "He recalled the sight of the full moon rising over the mountains.",
            "The childhood blanket still carried the faint scent of home.",
            "She remembered the sound of her name being called on graduation day.",
            "The old fishing rod brought back memories of quiet mornings on the lake.",
            "He recalled the feeling of the first snowfall of the season on his face.",
            "The vintage record player still played the songs of their courtship.",
            "She remembered the taste of the cake her mother baked for every birthday.",
            "The old compass pointed north just as it had on their hiking adventures.",
            "He recalled the sound of thunder rolling across the prairie as a boy.",
            "The childhood treehouse still stood, though smaller than he remembered.",
            "She remembered the feeling of diving into a cool lake on a hot day.",
            "The old yearbook contained faces and messages from a different era.",
            "He recalled the sight of the sunrise from the summit of the mountain.",
            "The handwritten recipe reminded her of standing on a stool beside her mother.",
            "She remembered the sound of the train whistle in the distance at night.",
            "The old pocket watch had belonged to his great-grandfather and still worked.",
            "He recalled the feeling of the first day of spring after a harsh winter.",
            "The childhood swing set creaked with the ghosts of countless afternoons.",
            "She remembered the taste of fresh strawberries picked straight from the garden.",
            "The old quilt was stitched from fabrics that each held a family story.",
            "He recalled the sound of his father whistling while working in the garage.",
            "The faded map showed the route of their first cross-country road trip.",
            "She remembered the feeling of accomplishment after building something with her hands.",
            "The old camera still held a roll of film from a day long forgotten.",
            "He recalled the sight of fireflies dancing in the summer twilight.",
            "The childhood fort made of blankets and chairs was a kingdom of imagination.",
            "She remembered the sound of her father reading bedtime stories every night.",
            "The old stone wall marked the boundary of land her family once owned.",
            "He recalled the feeling of the ocean breeze on a sailing adventure.",
            "The dried lavender in the drawer carried the scent of summers past.",
            "She remembered the taste of hot chocolate on cold winter evenings.",
            "The old garden gate opened to memories of tending flowers with her grandmother.",
            "He recalled the sound of the factory whistle marking the end of the workday.",
            "The childhood tree still stood, its trunk bearing the initials carved long ago.",
            "She remembered the feeling of the first day of school with a new backpack.",
            "The old piano still played the songs she had learned as a young girl.",
            "He recalled the sight of the harvest moon rising over the cornfields.",
            "The worn path through the woods was the route of countless childhood adventures.",
            "She remembered the taste of her first homemade meal that actually turned out well.",
            "The old lighthouse still stood, guiding ships just as it had for generations.",
            "He recalled the sound of his mother calling him home for dinner at dusk.",
            "The childhood creek still flowed, though the stones seemed smaller now.",
            "She remembered the feeling of the first snowball hitting her shoulder in play.",
            "The old barn held memories of summer days spent exploring every corner.",
            "He recalled the sight of the stars from the rooftop on clear summer nights.",
            "The weathered fence post marked where the old property line once ran.",
        ]
    },
    "auditory": {
        "expected": ["G7_sensory", "G2_wernicke"],
        "texts": [
            "The thunder rolled across the valley in deep resonant waves of sound.",
            "A lone flute played a haunting melody that echoed through the empty hall.",
            "The crackling fire popped and hissed as flames consumed the dry wood.",
            "Wind whispered through the pine trees creating a soft continuous rustling.",
            "The choir harmonies blended together in a rich tapestry of sound.",
            "The rain drummed steadily against the windowpane in a soothing rhythm.",
            "A distant train whistle pierced the quiet of the countryside night.",
            "The cello produced deep mournful tones that vibrated through the concert hall.",
            "Birds chirped in a dawn chorus that gradually grew louder with the sunrise.",
            "The piano keys produced a cascade of notes that filled the room.",
            "The waves crashed against the rocks with a thunderous roaring sound.",
            "A street musician played a lively tune on his accordion in the square.",
            "The saxophone wailed a bluesy melody that moved the audience to tears.",
            "Leaves crunched underfoot as they walked through the autumn forest.",
            "The organ pipes resonated with a powerful chord that shook the cathedral.",
            "Crickets chirped in a steady rhythm on the warm summer evening.",
            "The trumpet blasted a triumphant fanfare that echoed across the battlefield.",
            "Raindrops pattered against the tin roof in an irregular staccato pattern.",
            "The violin produced a soaring melody that seemed to touch the heavens.",
            "Frogs croaked in a chorus from the marsh at twilight.",
            "The drum beat a steady rhythm that made everyone want to dance.",
            "The wind howled through the narrow streets of the old city.",
            "A guitar strummed gentle chords around the campfire at night.",
            "The church bells rang out across the village marking the hour.",
            "The harp plucked delicate arpeggios that shimmered in the air.",
            "Thunder clapped directly overhead with a deafening crack of sound.",
            "The clarinet played a smooth jazz melody in the dimly lit club.",
            "Owls hooted in the dark forest calling to each other across the trees.",
            "The brass section blared a powerful crescendo that shook the seats.",
            "The stream babbled over smooth stones in the quiet woodland.",
            "The accordion wheezed and puffed a cheerful folk melody.",
            "Wolves howled in the distance their voices echoing across the tundra.",
            "The electric guitar screamed through the amplifier in a wall of sound.",
            "The ticking of the grandfather clock filled the silent hallway.",
            "The flute trilled a light playful melody like birdsong in spring.",
            "The bass guitar thumped a deep groove that resonated in the chest.",
            "The wind chime tinkled softly in the gentle evening breeze.",
            "The orchestra tuned their instruments in a cacophony before the concert.",
            "The whistle of the kettle rose to a sharp piercing note.",
            "The banjo plucked a rapid bluegrass melody with lightning speed.",
            "The thunderstorm rattled the windows with successive peals of thunder.",
            "The mandolin chimed bright notes in the traditional Irish tune.",
            "The waterfall roared continuously as tons of water plunged into the pool.",
            "The harmonica wailed a lonely blues melody on the front porch.",
            "The snare drum rattled with a military precision in the parade.",
            "The wind whistled through the cracks in the old cabin walls.",
            "The sitar produced exotic droning sounds that seemed from another dimension.",
            "The hail pelted the roof like a thousand tiny drumsticks.",
            "The timpani rolled with a deep rumbling that built tension.",
            "The brook gurgled and chuckled as it wound through the meadow.",
            "The bagpipes droned a haunting melody across the Scottish highlands.",
            "The ice cracked with sharp reports across the frozen lake.",
            "The vibraphone shimmered with sustained tones that seemed to float.",
            "The rain intensified to a roar on the metal roof of the barn.",
            "The oboe played a plaintive solo that cut through the orchestra.",
            "The geese honked in formation as they flew overhead in autumn.",
            "The synthesizer produced otherworldly sounds that seemed from another dimension.",
            "The gravel crunched under the tires of the approaching vehicle.",
            "The French horn called out with a rich mellow tone.",
            "The cicadas buzzed in a deafening chorus on the hottest day.",
            "The marimba produced warm wooden tones in a complex rhythmic pattern.",
            "The faucet dripped with an annoying regularity in the quiet bathroom.",
            "The trombone slid between notes with a smooth glissando effect.",
            "The snow fell silently muffling all sound in a white blanket.",
            "The xylophone clacked out a bright cheerful melody in the children song.",
            "The popcorn popped in rapid succession in the microwave.",
            "The bassoon produced a deep reedy tone that anchored the woodwinds.",
            "The river rushed over the rapids with a powerful roaring sound.",
            "The triangle chimed with a clear piercing ring that cut through the music.",
            "The bees buzzed industriously among the flowers in the garden.",
            "The tuba rumbled with the lowest notes in the brass section.",
            "The fireplace crackled and popped as the logs settled in the grate.",
            "The glockenspiel sparkled with high bell-like tones in the melody.",
            "The thunder grumbled in the distance promising an approaching storm.",
            "The English horn sang a mournful melody in the pastoral symphony.",
            "The leaves rustled in the wind like whispered secrets in the trees.",
            "The celesta produced ethereal bell-like tones in the dance of the sugar plum fairy.",
            "The dog barked rhythmically at the mail carrier approaching the door.",
            "The piccolo trilled high above the orchestra with brilliant clarity.",
            "The rain softened to a gentle patter on the garden leaves.",
            "The steel drum produced bright tropical tones in the Caribbean rhythm.",
            "The cat purred contentedly on the warm windowsill in the afternoon sun.",
            "The contrabassoon rumbled with the deepest tones in the woodwind section.",
            "The wind gusted through the canyon with a howling mournful sound.",
            "The gong resonated with a deep sustained tone that slowly faded.",
            "The children laughed and shouted in the playground with joyful noise.",
            "The lyre plucked gentle strings in the ancient Greek melody.",
            "The siren wailed in the distance growing louder with each passing second.",
            "The zither produced delicate plucked sounds in the traditional folk song.",
            "The waves lapped gently against the shore in a soothing rhythm.",
            "The receding storm left behind the sound of dripping water from the eaves.",
        ]
    },
}


def generate_stimulus_bank(output_path="data/stimulus_bank.json"):
    """Generate 1000-stimulus bank from predefined texts."""
    print("=" * 70)
    print("SGP-Tribe3 - Generating 1000-Stimulus Bank")
    print("=" * 70)

    stimuli = []
    stim_id = 1

    for category, data in CATEGORIES.items():
        texts = data["texts"]
        expected = data["expected"]

        print(f"\n  {category.capitalize()}: {len(texts)} stimuli")

        for text in texts:
            stimuli.append({
                "id": stim_id,
                "category": category,
                "text": text,
                "expected_dominant": expected,
            })
            stim_id += 1

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as f:
        json.dump({
            "date": datetime.now().isoformat(),
            "total_stimuli": len(stimuli),
            "categories": {cat: len(data["texts"]) for cat, data in CATEGORIES.items()},
            "stimuli": stimuli,
        }, f, indent=2)

    print(f"\n{'=' * 70}")
    print(f"STIMULUS BANK GENERATED")
    print(f"{'=' * 70}")
    print(f"Total stimuli: {len(stimuli)}")
    print(f"Categories: {len(CATEGORIES)}")
    print(f"Per category: {len(stimuli) // len(CATEGORIES)}")
    print(f"Output: {output_path}")


if __name__ == "__main__":
    generate_stimulus_bank()
